# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Smartlink' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!

  # Pods for Smartlink
  pod 'CocoaLumberjack'
#  pod 'CocoaLumberjack', '3.2.1'
  pod 'AFNetworking'
  pod 'Bugly'
end
